(function(){
const SESSION='sunbot_pricebook_v3_session',EMAIL='sunbot_pricebook_v3_email',app=document.getElementById('app');
const state={token:sessionStorage.getItem(SESSION)||'',email:sessionStorage.getItem(EMAIL)||'',boot:null,catalog:null,tab:'combos',lines:[],client:{name:'',type:'Trường mới'},context:{students:150,teachers:2},preview:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=v=>Number(v||0).toLocaleString('vi-VN')+' ₫',busy=v=>document.body.classList.toggle('busy',!!v);
async function call(action,payload){busy(true);try{return await QuotationApi.call(state.token,action,payload)}finally{busy(false)}}
function loginView(message=''){app.innerHTML=`<div class="wrap"><section class="panel login"><div class="brand"><div class="logo">S</div><div><h1>SUNBOT SALES PRICEBOOK</h1><small>Quotation V3 · dữ liệu động từ backend</small></div></div><h2>Đăng nhập</h2><div class="field"><label>Email công việc</label><input id="email" type="email" value="${esc(state.email)}"></div><div class="field"><label>PIN 6 số</label><input id="pin" type="password" inputmode="numeric" maxlength="6"></div><button class="btn" id="login">Đăng nhập</button>${message?`<p class="notice danger">${esc(message)}</p>`:''}<p class="help">Giá và quyền hiển thị chỉ được tải sau khi xác thực.</p></section></div>`;document.getElementById('login').onclick=login;document.getElementById('pin').onkeydown=e=>{if(e.key==='Enter')login()}}
async function login(){const email=document.getElementById('email').value.trim().toLowerCase(),pin=document.getElementById('pin').value.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return loginView('Email chưa hợp lệ.');if(!/^\d{6}$/.test(pin))return loginView('PIN phải gồm 6 số.');try{busy(true);const result=await QuotationApi.login(email,pin);state.token=result.token;state.email=email;sessionStorage.setItem(SESSION,result.token);sessionStorage.setItem(EMAIL,email);await load()}catch(e){loginView(e.message)}finally{busy(false)}}
async function load(){if(!state.token)return loginView();try{[state.boot,state.catalog]=await Promise.all([call('bootstrap'),call('catalog')]);render()}catch(e){if(/phiên|đăng nhập|token/i.test(e.message)){sessionStorage.removeItem(SESSION);state.token='';loginView('Phiên đăng nhập đã hết hạn.')}else loginView(e.message)}}
function logout(){sessionStorage.removeItem(SESSION);state.token='';state.catalog=null;loginView()}
function render(){const user=state.boot.user||{};app.innerHTML=`<div class="wrap"><header class="top"><div class="brand"><div class="logo">S</div><div><h1>SUNBOT SALES PRICEBOOK</h1><small>${esc(user.email)} · ${esc(user.role)} · ${esc(state.boot.pricebook_version)}</small></div></div><button class="btn secondary" id="logout">Đăng xuất</button></header><nav class="nav no-print"><button class="tab ${state.tab==='combos'?'active':''}" data-tab="combos">Cấu hình mẫu</button><button class="tab ${state.tab==='builder'?'active':''}" data-tab="builder">Tạo báo giá</button><button class="tab ${state.tab==='catalog'?'active':''}" data-tab="catalog">Danh mục</button><button class="tab ${state.tab==='history'?'active':''}" data-tab="history">Lịch sử</button></nav><main id="content"></main><footer class="footer">Mọi giá phát hành được backend tính lại và lưu snapshot. Frontend không chứa giá sàn.</footer></div>`;document.getElementById('logout').onclick=logout;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderContent()});renderContent()}
function renderContent(){if(state.tab==='builder')return renderBuilder();if(state.tab==='catalog')return renderCatalog();if(state.tab==='history')return renderHistory();renderCombos()}
const priceFor=id=>state.catalog.prices[id]||null,itemFor=id=>state.catalog.items.find(i=>i.item_id===id);
function chooseCombo(code){const combo=state.catalog.combos.find(c=>c.combo_code===code);state.lines=combo.components.map(c=>({item_id:c.component_item_id,quantity:String(c.condition_rule_id||'').startsWith('QUANTITY:')?Number(state.context[String(c.condition_rule_id).split(':')[1]]||1):Number(c.qty),can_edit:c.can_edit,required:c.required,quantity_source:String(c.condition_rule_id||'').startsWith('QUANTITY:')?String(c.condition_rule_id).split(':')[1]:'',inputs:{}}));state.tab='builder';state.preview=null;render()}
function renderCombos(){const el=document.getElementById('content');el.innerHTML=`<div class="notice ok"><b>Basic / Standard / Plus là cấu hình triển khai.</b> Tổng cuối luôn được tính lại từ Pricebook đang hiệu lực.</div><div class="grid" style="margin-top:14px">${state.catalog.combos.map(c=>`<article class="panel combo ${c.recommended?'recommended':''}"><div class="meta"><span class="badge">${esc(c.combo_code)}</span>${c.recommended?'<span class="badge">KHUYẾN NGHỊ</span>':''}</div><h3>${esc(c.name)}</h3><p>${esc(c.description)}</p><div class="price">${c.components.length} cấu phần</div><button class="btn" data-combo="${esc(c.combo_code)}">Chọn cấu hình</button></article>`).join('')}<article class="panel combo"><span class="badge">CUSTOM</span><h3>Tự cấu hình</h3><p>Chọn các hạng mục backend cho phép báo giá.</p><div class="price">Theo nhu cầu</div><button class="btn secondary" id="custom">Bắt đầu</button></article></div>`;document.querySelectorAll('[data-combo]').forEach(b=>b.onclick=()=>chooseCombo(b.dataset.combo));document.getElementById('custom').onclick=()=>{state.lines=[];state.tab='builder';render()}}
function options(){return state.catalog.items.filter(i=>i.quote_selectable&&priceFor(i.item_id)).map(i=>`<option value="${esc(i.item_id)}">${esc(i.category)} · ${esc(i.name)}</option>`).join('')}
function renderBuilder(){const el=document.getElementById('content');el.innerHTML=`<div class="two"><section class="panel no-print"><h2>Thông tin & cấu hình</h2><div class="field"><label>Khách hàng</label><input id="client" value="${esc(state.client.name)}" placeholder="Tên trường / đơn vị"></div><div class="three"><div class="field"><label>Loại khách</label><select id="clientType">${['Trường mới','Trường kế thừa','Operator','Camp / Event'].map(x=>`<option ${state.client.type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Số trẻ</label><input id="students" type="number" min="1" value="${state.context.students}"></div><div class="field"><label>Số giáo viên</label><input id="teachers" type="number" min="0" value="${state.context.teachers}"></div></div><div class="field"><label>Thêm hạng mục</label><div class="toolbar"><select id="newItem">${options()}</select><button class="btn secondary" id="add">Thêm</button></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Hạng mục</th><th>SL</th><th></th></tr></thead><tbody>${state.lines.map((l,i)=>{const item=itemFor(l.item_id);return`<tr><td><b>${esc(item?item.name:l.item_id)}</b><br><small>${esc(item?item.unit:'')}</small></td><td><input class="qty" type="number" min="1" value="${l.quantity}" data-qty="${i}" ${l.can_edit===false?'disabled':''}></td><td><button class="btn ghost" data-remove="${i}" ${l.required?'disabled':''}>Bỏ</button></td></tr>`}).join('')}</tbody></table></div><button class="btn" id="preview" style="margin-top:14px">Tính trên máy chủ</button></section><section class="panel"><h2>Báo giá xem trước</h2><div id="previewArea">${previewHtml()}</div></section></div>`;bindBuilder()}
function bindBuilder(){document.getElementById('client').oninput=e=>state.client.name=e.target.value;document.getElementById('clientType').onchange=e=>state.client.type=e.target.value;['students','teachers'].forEach(id=>document.getElementById(id).onchange=e=>{state.context[id]=Number(e.target.value||0);state.lines.filter(l=>l.quantity_source===id).forEach(l=>l.quantity=state.context[id]);state.preview=null;renderBuilder()});document.querySelectorAll('[data-qty]').forEach(x=>x.onchange=()=>{state.lines[Number(x.dataset.qty)].quantity=Number(x.value||1);state.preview=null;renderBuilder()});document.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{state.lines.splice(Number(x.dataset.remove),1);state.preview=null;renderBuilder()});document.getElementById('add').onclick=()=>{const id=document.getElementById('newItem').value;if(!id)return;const existing=state.lines.find(l=>l.item_id===id);existing?existing.quantity++:state.lines.push({item_id:id,quantity:1,can_edit:true,required:false,inputs:{}});state.preview=null;renderBuilder()};document.getElementById('preview').onclick=preview;const create=document.getElementById('create');if(create)create.onclick=createQuote}
function payload(){return{client:{name:state.client.name,type:state.client.type},context:state.context,lines:state.lines.map(l=>({item_id:l.item_id,quantity:l.quantity_source?Number(state.context[l.quantity_source]||0):l.quantity,inputs:Object.assign({},state.context,l.inputs||{})})).filter(l=>l.quantity>0)}}
async function preview(){if(!state.lines.length)return alert('Hãy chọn ít nhất một hạng mục.');try{state.preview=await call('preview',payload());renderBuilder()}catch(e){document.getElementById('previewArea').innerHTML=`<div class="notice danger">${esc(e.message)}</div>`}}
function previewHtml(){if(!state.preview)return'<div class="help">Chọn cấu hình và bấm “Tính trên máy chủ”. Frontend không tự quyết giá phát hành.</div>';const p=state.preview;return`<div class="table-wrap"><table class="table"><thead><tr><th>Hạng mục</th><th>SL</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody>${p.lines.map(l=>`<tr><td><b>${esc(l.name)}</b></td><td>${l.quantity}</td><td class="money">${money(l.unit_price)}</td><td class="money">${money(l.line_total)}</td></tr>`).join('')}</tbody></table></div><div class="summary" style="margin-top:16px"><div class="row"><span>Tạm tính</span><b>${money(p.subtotal)}</b></div><div class="row"><span>Điều chỉnh</span><b>-${money(p.discount)}</b></div><div class="row total"><span>Tổng</span><span>${money(p.final)}</span></div></div>${p.approval_required?'<div class="notice" style="margin-top:14px">Cấu hình này cần phê duyệt trước khi phát hành.</div>':'<div class="notice ok" style="margin-top:14px">Có thể lưu dự thảo.</div>'}<button class="btn" id="create" ${state.client.name.trim()?'':'disabled'}>Lưu dự thảo</button>`}
async function createQuote(){try{const result=await call('create',payload());alert(`Đã tạo ${result.quote_id} · ${result.status}`);state.tab='history';render()}catch(e){alert(e.message)}}
function renderCatalog(){document.getElementById('content').innerHTML=`<section class="panel"><h2>Danh mục theo quyền</h2><p class="help">Category và giá do backend trả về. Sales không nhận giá sàn.</p><div class="table-wrap"><table class="table"><thead><tr><th>Nhóm</th><th>Hạng mục</th><th>Đơn vị</th><th>Giá khuyến nghị</th></tr></thead><tbody>${state.catalog.items.map(i=>{const p=priceFor(i.item_id);return`<tr><td>${esc(i.category)}</td><td><b>${esc(i.name)}</b><br><small>${esc(i.item_id)}</small></td><td>${esc(i.unit)}</td><td class="money">${p?money(p.recommended_price):'Theo cấu hình'}</td></tr>`}).join('')}</tbody></table></div></section>`}
async function renderHistory(){const el=document.getElementById('content');el.innerHTML='<section class="panel help">Đang tải lịch sử…</section>';try{const rows=await call('history');el.innerHTML=`<section class="panel"><h2>Lịch sử báo giá</h2>${rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Mã</th><th>Khách hàng</th><th>Ngày</th><th>Phiên bản</th><th>Trạng thái</th><th>Tổng</th></tr></thead><tbody>${rows.map(q=>`<tr><td><b>${esc(q.quote_id)}</b></td><td>${esc(q.client_name)}</td><td>${esc(q.created_at)}</td><td>v${esc(q.version)}</td><td>${esc(q.status)}</td><td class="money">${money(q.final)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="help">Chưa có báo giá.</div>'}</section>`}catch(e){el.innerHTML=`<div class="notice danger">${esc(e.message)}</div>`}}
load();
})();
