function qv3MigrateOfficial2026() {
  qv3EnsureSchema_(); const actor=Session.getActiveUser().getEmail()||'migration';
  const items=[
    ['PRG-LT-3Y','PROGRAM','Quyền chương trình','Lập trình tư duy cùng Sunbot – 3 năm','Quyền tại 01 điểm trường','điểm','FIXED',''],['PRG-LT-5Y','PROGRAM','Quyền chương trình','Lập trình tư duy cùng Sunbot – 5 năm','Quyền tại 01 điểm trường','điểm','FIXED',''],
    ['PRG-STEAM-3Y','PROGRAM','Quyền chương trình','STEAM cùng Sunbot – 3 năm','Quyền tại 01 điểm trường','điểm','FIXED',''],['PRG-STEAM-5Y','PROGRAM','Quyền chương trình','STEAM cùng Sunbot – 5 năm','Quyền tại 01 điểm trường','điểm','FIXED',''],
    ['PRG-CORE-3Y','PROGRAM','Quyền chương trình','Sunbot Core – 2 phân môn – 3 năm','Quyền tại 01 điểm trường','điểm','FIXED',''],['PRG-CORE-5Y','PROGRAM','Quyền chương trình','Sunbot Core – 2 phân môn – 5 năm','Quyền tại 01 điểm trường','điểm','FIXED',''],
    ['HW-RBT-01','HARDWARE','Thiết bị','Robot Sunbot','Robot chính thức 2026','robot','FIXED',''],['HW-MAP-01','HARDWARE','Thiết bị','Bản đồ robot chuẩn','','bản','FIXED',''],['HW-OBS-01','MATERIAL','Học cụ Robotics','Bộ chướng ngại vật Sunbot chuẩn','','bộ','FIXED',''],['HW-CARD-01','MATERIAL','Học cụ Robotics','Bộ thẻ flashcard, thẻ đích, bản đồ giấy','','bộ','FIXED',''],['HW-BOX-01','HARDWARE','Thiết bị','Android Box','Có thể bỏ nếu thiết bị trường tương thích','bộ','FIXED',''],
    ['ST-KIT-Y1','MATERIAL','Học cụ STEAM','Bộ học cụ STEAM Sunbot – Năm 1','Tối đa 150 trẻ / 6 lớp / 35 bài','bộ/trường','FIXED',''],
    ['TR-1P-20','TRAINING','Đào tạo','Đào tạo giáo viên – 1 phân môn, ≤20 người','','đợt','FIXED',''],['TR-2P-20','TRAINING','Đào tạo','Đào tạo giáo viên – 2 phân môn, ≤20 người','','đợt','FIXED',''],
    ['TR-REF-1P','TRAINING','Tái đào tạo','Tái đào tạo & chuẩn hóa – 1 phân môn, ≤20 người','Không gồm sát hạch/chứng nhận','đợt/trường','FIXED',''],['TR-REF-2P','TRAINING','Tái đào tạo','Tái đào tạo & chuẩn hóa – 2 phân môn, ≤20 người','Không gồm sát hạch/chứng nhận','đợt/trường','FIXED',''],
    ['CERT-1P','SERVICE','Chứng nhận','Sát hạch & chứng nhận – 1 phân môn','Hiệu lực 24 tháng','giáo viên','FIXED',''],['CERT-2P','SERVICE','Chứng nhận','Sát hạch & chứng nhận – 2 phân môn','Hiệu lực 24 tháng','giáo viên','FIXED',''],
    ['SUPPORT-ANNUAL','SERVICE','Đồng hành','Gói đồng hành vận hành & bảo đảm chất lượng','Theo số trẻ','năm','TIERED','SUPPORT_BANDS_2026'],
    ['LEGACY-REACTIVATION','SERVICE','Trường kế thừa','Dịch vụ tái kích hoạt Sunbot','Không hồi tố quyền lịch sử','đợt','TIERED','LEGACY_DECISION'],
    ['OPERATOR-NETWORK','SERVICE','Operator','Phí mạng lưới Sunbot','Tính theo trẻ đăng ký và tiết hợp đồng','năm','FORMULA','OPERATOR_NETWORK_FEE']
  ];
  const priceMap={'PRG-LT-3Y':45000000,'PRG-LT-5Y':60000000,'PRG-STEAM-3Y':18000000,'PRG-STEAM-5Y':24000000,'PRG-CORE-3Y':60000000,'PRG-CORE-5Y':80000000,'HW-RBT-01':4800000,'HW-MAP-01':600000,'HW-OBS-01':1500000,'HW-CARD-01':1500000,'HW-BOX-01':1500000,'ST-KIT-Y1':16500000,'TR-1P-20':11000000,'TR-2P-20':19000000,'TR-REF-1P':5500000,'TR-REF-2P':8500000,'CERT-1P':500000,'CERT-2P':800000,'SUPPORT-ANNUAL':0,'LEGACY-REACTIVATION':0,'OPERATOR-NETWORK':0};
  const floorMap={'PRG-LT-3Y':42000000,'PRG-LT-5Y':56000000,'PRG-STEAM-3Y':17000000,'PRG-STEAM-5Y':22000000,'PRG-CORE-3Y':56000000,'PRG-CORE-5Y':75000000,'HW-RBT-01':4600000,'ST-KIT-Y1':15500000,'TR-1P-20':10000000,'TR-2P-20':17500000,'CERT-1P':450000,'CERT-2P':750000};
  items.forEach(function(x,i){qv3Upsert_('CATALOG_ITEMS','item_id',{item_id:x[0],item_type:x[1],category:x[2],name:x[3],description:x[4],unit:x[5],status:'ACTIVE',sales_visible:true,customer_visible:true,quote_selectable:true,price_mode:x[6],pricing_rule_id:x[7],sort_order:i+1,tags:x[1]+','+x[2],source_ref:'SUNBOT_PRICEBOOK_MASTER_2026_CHINH_THUC',metadata_json:'{}',updated_at:new Date(),updated_by:actor});const priceId='PV-20260824-'+x[0];if(!qv3Rows_('PRICE_VERSIONS').some(function(p){return String(p.price_id)===priceId}))qv3Append_('PRICE_VERSIONS',{price_id:priceId,item_id:x[0],list_price:priceMap[x[0]],recommended_price:priceMap[x[0]],floor_price:floorMap[x[0]]==null?priceMap[x[0]]:floorMap[x[0]],valid_from:new Date('2026-08-24'),currency:'VND',approved_by:actor,approved_at:new Date()})});
  const rules=[
    {rule_id:'SUPPORT_BANDS_2026',rule_type:'TIER',input_schema:'{"students":"number"}',expression:JSON.stringify({input:'students',tiers:[{code:'A',max:150,amount:12000000},{code:'B',max:300,amount:15000000},{code:'C',max:500,amount:18000000},{code:'D',max:null,amount:24000000}]})},
    {rule_id:'LEGACY_DECISION',rule_type:'TIER',input_schema:'{"legacy_score":"number","legal_override":"boolean"}',expression:JSON.stringify({input:'legacy_score',tiers:[{code:'A',max:2,amount:5000000},{code:'B',max:5,amount:8000000},{code:'C',max:null,amount:12000000}]})},
    {rule_id:'OPERATOR_NETWORK_FEE',rule_type:'FORMULA',input_schema:'{"learners":"number","sessions":"number","core_tuition":"number"}',expression:JSON.stringify({formula:'OPERATOR_NETWORK_FEE',unit_price:4000,cap_rate:.12})}
  ]; rules.forEach(function(r){if(!qv3Rows_('PRICING_RULES').some(function(x){return String(x.rule_id)===r.rule_id&&String(x.version)==='2026.1'}))qv3Append_('PRICING_RULES',Object.assign(r,{effective_from:new Date('2026-08-24'),version:'2026.1',status:'ACTIVE'}))});
  const combos={BASIC:[['PRG-LT-3Y',1,false],['HW-RBT-01',3,true],['HW-MAP-01',2,true],['HW-OBS-01',2,true],['HW-CARD-01',1,true],['HW-BOX-01',1,true],['TR-1P-20',1,false],['CERT-1P',1,true,'QUANTITY:teachers'],['SUPPORT-ANNUAL',1,false]],STANDARD:[['PRG-CORE-3Y',1,false],['HW-RBT-01',4,true],['HW-MAP-01',3,true],['HW-OBS-01',2,true],['HW-CARD-01',1,true],['HW-BOX-01',1,true],['ST-KIT-Y1',1,true],['TR-2P-20',1,false],['CERT-2P',1,true,'QUANTITY:teachers'],['SUPPORT-ANNUAL',1,false]],PLUS:[['PRG-CORE-5Y',1,false],['HW-RBT-01',6,true],['HW-MAP-01',5,true],['HW-OBS-01',5,true],['HW-CARD-01',1,true],['HW-BOX-01',1,true],['ST-KIT-Y1',1,true],['TR-2P-20',1,false],['CERT-2P',1,true,'QUANTITY:teachers'],['SUPPORT-ANNUAL',1,false]]};
  Object.keys(combos).forEach(function(code,ci){qv3Upsert_('COMBO_DEFINITIONS','combo_code',{combo_code:code,name:'Sunbot '+code[0]+code.slice(1).toLowerCase(),description:code==='STANDARD'?'Cấu hình cân bằng, khuyến nghị cho đa số trường mới.':'Cấu hình triển khai có thể tinh chỉnh.',status:'ACTIVE',recommended:code==='STANDARD',sort_order:ci+1});combos[code].forEach(function(c,i){qv3UpsertComposite_('COMBO_COMPONENTS',['combo_code','component_item_id'],{combo_code:code,component_item_id:c[0],qty:c[1],required:!c[2],can_edit:c[2],condition_rule_id:c[3]||(c[0]==='SUPPORT-ANNUAL'?'SUPPORT_BANDS_2026':''),line_order:i+1})})});
  [['Sales',false,0,false,false],['Leader',true,.05,true,false],['CEO',true,1,true,false],['Admin',true,0,false,true]].forEach(function(p){qv3Upsert_('PERMISSIONS','role',{role:p[0],can_view_floor:p[1],max_discount:p[2],can_approve:p[3],can_admin_catalog:p[4]})});
  qv3Audit_('MIGRATION',actor,QV3_CONFIG.PRICEBOOK_VERSION,null,{items:items.length,rules:rules.length,combos:Object.keys(combos)}); return {ok:true,items:items.length,rules:rules.length,combos:Object.keys(combos).length};
}
