function qv3Bootstrap_(auth) { return {user:{user_id:auth.user.user_id,email:auth.user.email,role:auth.user.role},capabilities:qv3PublicPermission_(auth.permission),pricebook_version:QV3_CONFIG.PRICEBOOK_VERSION,feature_flags:{approvals:true,legacy:true,operator:true}}; }

function qv3Catalog_(auth) {
  const role=String(auth.user.role), canFloor=qv3Bool_(auth.permission.can_view_floor);
  const items=qv3Rows_('CATALOG_ITEMS').filter(function(i){return String(i.status)==='ACTIVE' && (role!=='Sales'||qv3Bool_(i.sales_visible))}).sort(function(a,b){return Number(a.sort_order)-Number(b.sort_order)}).map(function(i){return Object.assign({},i,{sales_visible:qv3Bool_(i.sales_visible),customer_visible:qv3Bool_(i.customer_visible),quote_selectable:qv3Bool_(i.quote_selectable),metadata:qv3Json_(i.metadata_json,{})})});
  const prices={}; items.forEach(function(i){const p=qv3ActivePrice_(i.item_id);if(p){prices[i.item_id]={price_id:p.price_id,list_price:Number(p.list_price),recommended_price:Number(p.recommended_price),currency:p.currency||'VND'};if(canFloor)prices[i.item_id].floor_price=Number(p.floor_price)}});
  const combos=qv3Rows_('COMBO_DEFINITIONS').filter(function(c){return String(c.status)==='ACTIVE'}).map(function(c){return Object.assign({},c,{recommended:qv3Bool_(c.recommended),components:qv3Rows_('COMBO_COMPONENTS').filter(function(x){return String(x.combo_code)===String(c.combo_code)}).sort(function(a,b){return Number(a.line_order)-Number(b.line_order)}).map(function(x){return Object.assign({},x,{qty:Number(x.qty),required:qv3Bool_(x.required),can_edit:qv3Bool_(x.can_edit)})})})});
  return {categories:Array.from(new Set(items.map(function(i){return i.category}))),items:items,prices:prices,combos:combos};
}

function qv3Json_(v,fallback){try{return v&&typeof v==='string'?JSON.parse(v):v||fallback}catch(e){return fallback}}
function qv3Preview_(auth,payload){const items=qv3Rows_('CATALOG_ITEMS'),prices=items.map(function(i){return qv3ActivePrice_(i.item_id)}).filter(Boolean),rules=qv3Rows_('PRICING_RULES').filter(function(r){return String(r.status)==='ACTIVE'});const result=qv3ComputePreview_(items,prices,rules,payload,auth.permission);result.lines.forEach(function(l){delete l._floor});return result;}

function qv3Create_(auth,payload) {
  const computed=qv3ComputePreview_(qv3Rows_('CATALOG_ITEMS'),qv3Rows_('CATALOG_ITEMS').map(function(i){return qv3ActivePrice_(i.item_id)}).filter(Boolean),qv3Rows_('PRICING_RULES').filter(function(r){return String(r.status)==='ACTIVE'}),payload,auth.permission);
  const quoteId='Q-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMdd')+'-'+Utilities.getUuid().slice(0,8).toUpperCase(), version=1, status=computed.approval_required?'PENDING_APPROVAL':'DRAFT', now=new Date();
  const snapshot=JSON.stringify({client:payload.client,context:payload.context,lines:computed.lines.map(function(l){const x=Object.assign({},l);delete x._floor;return x})});
  qv3Append_('QUOTES',{quote_id:quoteId,quote_version:version,client_id:(payload.client||{}).id||'',client_name:(payload.client||{}).name||'',created_by:auth.user.email,created_at:now,status:status,pricebook_version:QV3_CONFIG.PRICEBOOK_VERSION,rule_version:'2026.1',subtotal:computed.subtotal,discount:computed.discount,final:computed.final,approval_required:computed.approval_required,context_json:JSON.stringify(payload.context||{}),snapshot_hash:Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,snapshot))});
  computed.lines.forEach(function(l,i){qv3Append_('QUOTE_LINES',{quote_id:quoteId,quote_version:version,line_no:i+1,item_id:l.item_id,name_snapshot:l.name,description_snapshot:l.description,unit_snapshot:l.unit,quantity:l.quantity,list_price_snapshot:l.list_price,recommended_price_snapshot:l.recommended_price,unit_price_snapshot:l.unit_price,line_total:l.line_total,price_id:l.price_id,rule_id:l.rule_id,rule_version:l.rule_version,customer_visible:l.customer_visible,metadata_json:JSON.stringify({approval_reason:l.approval_reason})})});
  qv3Audit_('QUOTE_CREATE',auth.user.email,quoteId,null,{version:version,status:status,final:computed.final});
  return {quote_id:quoteId,version:version,status:status,approval_required:computed.approval_required,snapshot:{client:payload.client,context:payload.context,lines:computed.lines.map(function(l){const x=Object.assign({},l);delete x._floor;return x}),subtotal:computed.subtotal,discount:computed.discount,final:computed.final,pricebook_version:QV3_CONFIG.PRICEBOOK_VERSION}};
}

function qv3History_(auth){const role=String(auth.user.role);return qv3Rows_('QUOTES').filter(function(q){return role!=='Sales'||String(q.created_by).toLowerCase()===String(auth.user.email).toLowerCase()}).map(function(q){return {quote_id:q.quote_id,version:q.quote_version,client_name:q.client_name,created_at:q.created_at,status:q.status,final:Number(q.final),pricebook_version:q.pricebook_version}})}
function qv3Get_(auth,payload){const q=qv3Rows_('QUOTES').find(function(x){return String(x.quote_id)===String(payload.quote_id)&&Number(x.quote_version)===Number(payload.version||x.quote_version)});if(!q)throw new Error('Không tìm thấy báo giá.');if(String(auth.user.role)==='Sales'&&String(q.created_by).toLowerCase()!==String(auth.user.email).toLowerCase())throw new Error('Không có quyền xem báo giá này.');return {quote:q,lines:qv3Rows_('QUOTE_LINES').filter(function(l){return String(l.quote_id)===String(q.quote_id)&&Number(l.quote_version)===Number(q.quote_version)})};}
function qv3SubmitApproval_(auth,payload){const rows=qv3Rows_('QUOTES').filter(function(q){return String(q.quote_id)===String(payload.quote_id)}).sort(function(a,b){return Number(b.quote_version)-Number(a.quote_version)}),q=rows[0];if(!q)throw new Error('Không tìm thấy báo giá.');if(String(q.created_by).toLowerCase()!==String(auth.user.email).toLowerCase()&&!qv3Bool_(auth.permission.can_approve))throw new Error('Không có quyền gửi duyệt.');if(String(q.status)!=='DRAFT')throw new Error('Chỉ DRAFT mới được gửi duyệt.');const saved=qv3UpsertComposite_('QUOTES',['quote_id','quote_version'],Object.assign({},q,{status:'PENDING_APPROVAL',approval_required:true}));qv3Audit_('APPROVAL',auth.user.email,q.quote_id,q,{status:'PENDING_APPROVAL',reason:payload.reason||''});return{quote_id:q.quote_id,version:q.quote_version,status:saved.status}}
function qv3ItemDetail_(auth,payload){const catalog=qv3Catalog_(auth),item=catalog.items.find(function(i){return String(i.item_id)===String(payload.item_id)});if(!item)throw new Error('Không tìm thấy hạng mục hoặc không có quyền xem.');return{item:item,active_price:catalog.prices[item.item_id]||null,compatible_items:[]}}
function qv3Combo_(auth,payload){const combo=qv3Catalog_(auth).combos.find(function(c){return String(c.combo_code)===String(payload.combo_code)});if(!combo)throw new Error('Không tìm thấy combo.');return combo}
